import ArtistModel from "@/models/artist-model";

export function GET(req) {
  const artistData: ArtistModel[] = [
    {
      Image:
        "https://www.google.com/url?sa=i&url=https://en.wikipedia.org/wiki/Shreya_Ghoshal&psig=AOvVaw0_15kQ6k06aQy-i4t6n88u&ust=1719321404094000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCLjJ043H7oYDFQAAAAAdAAAAABAE",
      Name: "Shreya Ghoshal",
      Category: "Singer",
      Range: ">50 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image:
        "https://www.google.com/url?sa=i&url=https://en.wikipedia.org/wiki/Arijit_Singh&psig=AOvVaw0_15kQ6k06aQy-i4t6n88u&ust=1719321404094000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCLjJ043H7oYDFQAAAAAdAAAAABAI",
      Name: "Arijit Singh",
      Category: "Singer",
      Range: ">50 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image:
        "https://www.google.com/url?sa=i&url=https://en.wikipedia.org/wiki/Sunidhi_Chauhan&psig=AOvVaw0_15kQ6k06aQy-i4t6n88u&ust=1719321404094000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCLjJ043H7oYDFQAAAAAdAAAAABAM",
      Name: "Sunidhi Chauhan",
      Category: "Singer",
      Range: "30-50 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://www.gettyimages.in/photos/justin-bieber",
      Name: "Justin Bieber",
      Category: "Singer",
      Range: ">50 Lakh",
      Location: "U.S.A",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://www.gettyimages.com/photos/ap-dhillon",
      Name: "AP Dhillon",
      Category: "Singer",
      Range: "30-50 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://www.gettyimages.in/photos/actress-nora",
      Name: "Nora Fatehi",
      Category: "Dancer",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://en.wikipedia.org/wiki/Remo_D%27Souza",
      Name: "Remo D'Souza",
      Category: "Dancer",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://en.wikipedia.org/wiki/Prabhu_Deva",
      Name: "Prabhu Deva",
      Category: "Dancer",
      Range: ">50 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "invalid_url",
      Name: "Suresh Mukund",
      Category: "Dancer",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "invalid_url",
      Name: "Sukhbir Singh",
      Category: "Singer",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://in.bookmyshow.com/person/dj-chetas/34711",
      Name: "DJ Chetas",
      Category: "DJ",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://www.shutterstock.com/editorial/search/dj-snake",
      Name: "DJ Snake",
      Category: "DJ",
      Range: "30-50 Lakh",
      Location: "U.S.A",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://www.gettyimages.com.au/photos/nucleya",
      Name: "Nucleya",
      Category: "DJ",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://iflyer.tv/en/artist/54667/",
      Name: "DJ Akira",
      Category: "DJ",
      Range: "<10 Lakh",
      Location: "U.K.",
      CTA: "Ask for Quote",
    },
    {
      Image: "invalid_url",
      Name: "Zakir Khan",
      Category: "Comedian",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "invalid_url",
      Name: "Vir Das",
      Category: "Comedian",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image:
        "https://www.reddit.com/r/IndianStandUpComedy/comments/1l41wdi/kenny_sebastian_generational_drama_stand_up_comedy/",
      Name: "Kenny Sebastian",
      Category: "Comedian",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "invalid_url",
      Name: "Trevor Noah",
      Category: "Comedian",
      Range: ">50 Lakh",
      Location: "U.S.A",
      CTA: "Ask for Quote",
    },
    {
      Image: "invalid_url",
      Name: "Sorabh Pant",
      Category: "Comedian",
      Range: "<10 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://en.wikipedia.org/wiki/Ranveer_Brar",
      Name: "Ranveer Brar",
      Category: "Comedian",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://en.wikipedia.org/wiki/Karan_Singh_(magician)",
      Name: "Karan Singh Magic",
      Category: "Magician",
      Range: "<10 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://en.wikipedia.org/wiki/Nilamadhav_Temple",
      Name: "Neel Madhav",
      Category: "Magician",
      Range: "<10 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "invalid_url",
      Name: "Shin Lim",
      Category: "Magician",
      Range: ">50 Lakh",
      Location: "U.S.A",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://en.wikipedia.org/wiki/P._C._Sorcar_Jr.",
      Name: "P.C. Sorcar Jr.",
      Category: "Magician",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "invalid_url",
      Name: "Sukhwinder Singh",
      Category: "Singer",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://en.wikipedia.org/wiki/Ashley_Lobo",
      Name: "Ashley Lobo",
      Category: "Dancer",
      Range: "10-30 Lakh",
      Location: "Australia",
      CTA: "Ask for Quote",
    },
    {
      Image:
        "https://www.reddit.com/r/IndianHipHopHeads/comments/1ld0rh7/emiway_bantai_paisa_paisa/",
      Name: "Emiway Bantai",
      Category: "Singer",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://www.gettyimages.com/photos/salim-merchant",
      Name: "Salim Merchant",
      Category: "Singer",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image:
        "https://www.reddit.com/r/IndianStandUpComedy/comments/1jmcvli/rahul_subramanian_2025_melbourne_international/",
      Name: "Rahul Subramanian",
      Category: "Comedian",
      Range: "<10 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image: "https://www.deezer.com/us/artist/9919358",
      Name: "DJ Kiran Kamath",
      Category: "DJ",
      Range: "<10 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image:
        "https://www.aninews.in/news/entertainment/bollywood/earlier-it-was-very-difficult-to-dream-of-becoming-an-artist-singer-jubin-nautiyal-hails-evolution-of-indian-music-industry20250624191216/",
      Name: "Jubin Nautiyal",
      Category: "Singer",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Badshah_at_the_promotion_of_his_song_%22Players%22.jpg/440px-Badshah_at_the_promotion_of_his_song_%22Players%22.jpg",
      Name: "Badshah",
      Category: "Singer",
      Range: "30-50 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Guru_Randhawa_at_the_promotion_of_his_song_%22Lahore%22.jpg/440px-Guru_Randhawa_at_the_promotion_of_his_song_%22Lahore%22.jpg",
      Name: "Guru Randhawa",
      Category: "Singer",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Honey_Singh_at_Mirchi_Music_Awards_2013.jpg/440px-Honey_Singh_at_Mirchi_Music_Awards_2013.jpg",
      Name: "Yo Yo Honey Singh",
      Category: "Singer",
      Range: "30-50 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Armaan_Malik_at_the_Global_Teacher_Prize_2016.jpg/440px-Armaan_Malik_at_the_Global_Teacher_Prize_2016.jpg",
      Name: "Armaan Malik",
      Category: "Singer",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
    {
      Image:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Armaan_Malik_at_the_Global_Teacher_Prize_2016.jpg/440px-Armaan_Malik_at_the_Global_Teacher_Prize_2016.jpg",
      Name: "Armaan Malik",
      Category: "Singer",
      Range: "10-30 Lakh",
      Location: "India",
      CTA: "Ask for Quote",
    },
  ];

  return new Response(
    JSON.stringify({
      success: true,
      message: "Data Fetched Successfully",
      data: artistData,
    }),
    {
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
}
